### ISSUE TITLE
F-56 Dificultad para actualizar a webpack 5

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sip#56]
* webpack 5 requiere expose-loader 2.0 o más reciente
* La sintaxis que empleamos en config/webpack/environment.js es para expose-loader 1.0.0 (actualizada en Mayo 2021) no es soportada por expose-loader 2.0.
* Hay problemas entre webpacker 5 y webpack 5
```
Compiling...                                                                                                                                           [8/27556]
Compilation failed:                                                                                                                                             
[webpack-cli] Failed to load '/restovar/vtamara/comp/rails/heb412-bs5/config/webpack/production.js' config                                                      
[webpack-cli] TypeError: Cannot read property 'plugins' of undefined                                                                                            
    at Object.<anonymous> (/restovar/vtamara/comp/rails/heb412-bs5/config/webpack/environment.js:4:13)                                                          
    at Module._compile (/restovar/vtamara/comp/rails/heb412-bs5/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)                                       
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)                                                                                   
    at Module.load (internal/modules/cjs/loader.js:1002:32)                                                                                                     
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)                                                                                            
    at Module.require (internal/modules/cjs/loader.js:1044:19)                  
    at require (/restovar/vtamara/comp/rails/heb412-bs5/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
```

**Comment by vtamara** [comment]
Se intenta con versión de master de webpacker, que al momento de este escrito actualiza 6.0.0-beta7.
Con la respectiva gema e instrucciones de https://github.com/rails/webpacker/commit/5a1d0bdc6eea2a40f3b1ce482f20351b7c0c160f

**Comment by vtamara** [comment]
Continua en #62
